export const mockDataTeam = [
  {
    id: 1,
    name: "Jon Snow",
    email: "jonsnow@gmail.com",
    age: 35,
    phone: "(665)121-5454",
    access: "admin",
  },
  {
    id: 2,
    name: "Cersei Lannister",
    email: "cerseilannister@gmail.com",
    age: 42,
    phone: "(421)314-2288",
    access: "manager",
  },
  {
    id: 3,
    name: "Jaime Lannister",
    email: "jaimelannister@gmail.com",
    age: 45,
    phone: "(422)982-6739",
    access: "user",
  },
  {
    id: 4,
    name: "Anya Stark",
    email: "anyastark@gmail.com",
    age: 16,
    phone: "(921)425-6742",
    access: "admin",
  },
  {
    id: 5,
    name: "Daenerys Targaryen",
    email: "daenerystargaryen@gmail.com",
    age: 31,
    phone: "(421)445-1189",
    access: "user",
  },
  {
    id: 6,
    name: "Ever Melisandre",
    email: "evermelisandre@gmail.com",
    age: 150,
    phone: "(232)545-6483",
    access: "manager",
  },
  {
    id: 7,
    name: "Ferrara Clifford",
    email: "ferraraclifford@gmail.com",
    age: 44,
    phone: "(543)124-0123",
    access: "user",
  },
  {
    id: 8,
    name: "Rossini Frances",
    email: "rossinifrances@gmail.com",
    age: 36,
    phone: "(222)444-5555",
    access: "user",
  },
  {
    id: 9,
    name: "Harvey Roxie",
    email: "harveyroxie@gmail.com",
    age: 65,
    phone: "(444)555-6239",
    access: "admin",
  },
];

export const mockDataSubscribes = [
  {
    id: 1,
    condition: "#ebdb01",
    loginName: "demo1",
    firstName: "Rick",
    lastName: "James",
    endDate: "2021-10-08 13:06:00",
    continueTo: "Manager_2",
    package: "slow",
    loans: 0,
    dailyConsumption: 0,
    remainingDays: 0,
  },
  {
    id: 2,
    condition: "#ebdb01",
    loginName: "demo1",
    firstName: "Rick",
    lastName: "James",
    endDate: "2021-10-08 13:06:00",
    continueTo: "Manager_2",
    package: "slow",
    loans: 0,
    dailyConsumption: 0,
    remainingDays: 0,
  },
  {
    id: 3,
    condition: "#ebdb01",
    loginName: "demo1",
    firstName: "Rick",
    lastName: "James",
    endDate: "2021-10-08 13:06:00",
    continueTo: "Manager_2",
    package: "slow",
    loans: 0,
    dailyConsumption: 0,
    remainingDays: 0,
  },
  {
    id: 4,
    condition: "#ebdb01",
    loginName: "demo1",
    firstName: "Rick",
    lastName: "James",
    endDate: "2021-10-08 13:06:00",
    continueTo: "Manager_2",
    package: "slow",
    loans: 0,
    dailyConsumption: 0,
    remainingDays: 0,
  },
  {
    id: 5,
    condition: "#ebdb01",
    loginName: "demo1",
    firstName: "Rick",
    lastName: "James",
    endDate: "2021-10-08 13:06:00",
    continueTo: "Manager_2",
    package: "slow",
    loans: 0,
    dailyConsumption: 0,
    remainingDays: 0,
  },
];

export const mockDataInvoices = [
  {
    id: 1,
    name: "Jon Snow",
    email: "jonsnow@gmail.com",
    cost: "21.24",
    phone: "(665)121-5454",
    date: "03/12/2022",
  },
  {
    id: 2,
    name: "Cersei Lannister",
    email: "cerseilannister@gmail.com",
    cost: "1.24",
    phone: "(421)314-2288",
    date: "06/15/2021",
  },
  {
    id: 3,
    name: "Jaime Lannister",
    email: "jaimelannister@gmail.com",
    cost: "11.24",
    phone: "(422)982-6739",
    date: "05/02/2022",
  },
  {
    id: 4,
    name: "Anya Stark",
    email: "anyastark@gmail.com",
    cost: "80.55",
    phone: "(921)425-6742",
    date: "03/21/2022",
  },
  {
    id: 5,
    name: "Daenerys Targaryen",
    email: "daenerystargaryen@gmail.com",
    cost: "1.24",
    phone: "(421)445-1189",
    date: "01/12/2021",
  },
  {
    id: 6,
    name: "Ever Melisandre",
    email: "evermelisandre@gmail.com",
    cost: "63.12",
    phone: "(232)545-6483",
    date: "11/02/2022",
  },
  {
    id: 7,
    name: "Ferrara Clifford",
    email: "ferraraclifford@gmail.com",
    cost: "52.42",
    phone: "(543)124-0123",
    date: "02/11/2022",
  },
  {
    id: 8,
    name: "Rossini Frances",
    email: "rossinifrances@gmail.com",
    cost: "21.24",
    phone: "(222)444-5555",
    date: "05/02/2021",
  },
];

export const mockDataUserTickets = [
  {
    id: 1,
    date: "2023-06-02 02:28:25",
    subject: "test for internet",
    firstName: "Rick",
    data: "James",
    secondName: "demo1",
    status: "closed ,unsolved",
  },
];

export const mockDataManagers = [
  {
    id: 1,
    loginName: "demo1",
    firstName: "Rick",
    lastName: "James",
    balance: "2021-10-08 13:06:00",
    loans: "Manager_2",
    validity: "slow",
    followMe: 0,
    numberSubscribers: 0,
  },
  {
    id: 2,
    loginName: "demo1",
    firstName: "Rick",
    lastName: "James",
    balance: "2021-10-08 13:06:00",
    loans: "Manager_2",
    validity: "slow",
    followMe: 0,
    numberSubscribers: 0,
  },
];

export const mockDataInvoicesManagers = [
  {
    id: 1,
    invoiceNumber: "2021-1-45",
    date: "2021-09-08 07:12:17",
    amount: "withdrawal",
    details: "10.00",
    publishedBy: "withdrawal of $ 10.00 ",
    paymentMethod: "admin",
    paid: true,
  },
];

export const mockDataReceiptManagers = [
  {
    id: 1,
    receiptDate: "2021-1-7",
    date: "2021-09-08 07:12:17",
    type: "deposit",
    amount: "withdrawal",
    details: "10.00",
    publishedBy: "withdrawal of $ 10.00 ",
  },
];
export const mockDataRegisterAccountsManagers = [
  {
    id: 1,
    date: "2021-1-7 07:12:17",
    credit: "admin",
    debit: "Manager_1",
    amount: "10.00",
    balance: "10.00",
    process: "withdrawal",
    details: "",
  },
];

export const mockDataNas = [
  {
    id: 1,
    name: "demo1",
    ipAddress: "0.0.0.0",
    type: "Mikrotik",
    secret: "12345",
    rtt: "0",
    onlineUser: "-",
    packetLoss: "-",
  },
];

export const mockDataPackages = [
  {
    id: 1,
    name: "Standard",
    price: "$ 50.00",
    poolName: "any",
    loadingSpeed: "5 Mb/s",
    paymentSpeed: "2 Mb/s",
    type: "Prepaid",
    subscriptionDuration: "1 Month(s)",
    subscribers: "1",
    onlineSubscribers: "0",
  },
];

export const mockDataCardsJobs = [
  {
    id: 1,
    type: "Refill",
    owner: "admin",
    creator: "admin",
    dateAdded: " 2023-01-17 16:15:42",
    quantity: "5",
    cardValue: "",
    profile: "",
    series: "1-2023",
    status: "Finished",
  },
];

export const mockDataSubscriberInvoices = [
  {
    id: 1,
    invoiceNo: "2023-1-33049",
    dueDate: "2023-06-04 18:50:19",
    username: "dem02",
    type: "acp_activation",
    amount: "100.00",
    description: "activated user using manager balance	",
    createdBy: "admin",
    paymentMethod: "",
    paid: "yes",
  },
];

export const mockDataReportsActivations = [
  {
    id: 1,
    history: "2023-1-33049",
    loginName: "demo1",
    firstName: "Rick",
    secondName: "James",
    manager: "admin",
    service: "slow",
    price: "$ 20.00",
    previousEndDate: "2021-09-08 13",
    laterExpiryDate: "2021-09-08 13",
    activationMethod: "credit",
    numberActivations: "2",
    status: "ok",
  },
];
